### ISSUE TITLE
...

### ISSUE THREAD

**Issue by LC6LW** [kuaidi100-api/php-demo#1]
啊啊啊

**Comment by kuaidi100-api** [comment]
您好，接口对接造成您的不便非常抱歉，方便的话麻烦添加QQ,我们拉技术群对接，谢谢您的支持！

 

任何问题，欢迎随时联系您的客户经理

Huitong Zhang 张慧彤

Shenzhen Qianhai Baidi Network Co. Ltd.深圳前海百递网络有限公司

Tel ：400 0000 387 / 19926654047(微信同号）

QQ：2504256701

Email :  <mailto:huitong_zhang@kuaidi100.com> huitong_zhang@kuaidi100.com

Add：深圳市南山区科技南十二路2号金蝶软件园

Website: 快递100( <http://www.kuaidi100.com/> www.kuaidi100.com)  API开放平台（ <http://api.kuaidi100.com/> http://api.kuaidi100.com/）

 

此邮件信息仅供收件人查阅，所含任何评论、陈述或数据仅供收件人参考，若有改动，恕可能不另行通知。未经深圳前海百递网络有限公司书面许可，请勿披露、复制、转载此邮件信息。任何第三方均不得查阅或使用此邮件信息。若您误收到本邮件，敬请及时通知发件人，并将邮件从您系统中彻底删除。发件人及深圳前海百递网络有限公司均不对因邮件可能引发的损失负责。



This message is intended only for use of the addressees and any comment, statement or data contained herein is for the reference of the receivers only. Notification may not be sent for any revising related. Please do not disclose, copy, or distribute this e-mail without Kuaidi100 written permission. Any third party shall not read or use the content of this e-mail. If you receive this e-mail in error, please notify the sender immediately and delete this e-mail from your computer system completely.The sender and Kuaidi100 are not responsible for the loss caused possibly by e-mail.

 

 

 

发件人: sai99110 [mailto:notifications@github.com] 
发送时间: 2020年11月1日 12:51
收件人: kuaidi100-api/php-demo <php-demo@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kuaidi100-api/php-demo] 垃圾 (#1)

 

接口文档写的那么垃圾，接口也那么垃圾醉了

**Comment by sai99110** [comment]
11
